### ISSUE TITLE
Trying to build docker image give error "The command '/bin/sh -c yarn install --frozen-lockfile' returned a non-zero code: 133"

### ISSUE THREAD

**Issue by aleJohnny** [QingWei-Li/notea#87]
I'm trying to build a docker image for armv7 using the Dockerfile in the repo, (run notea on rpi3)

$ git clone 
$ docker build .

But I'm getting a error in step 4:

```
Step 4/14 : RUN yarn install --frozen-lockfile
 ---> Running in acd792e440da


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7ec1f5f4
The command '/bin/sh -c yarn install --frozen-lockfile' returned a non-zero code: 133
```

I'm not so expert in docker, so maybe I'm forgetting something?
Couldn't find anything related....

**Comment by QingWei-Li** [comment]
I don't know much about docker. Is it necessary to deploy on Raspberry Pi? You can try to deploy it to Vercel or Netlify, which will be much easier.

**Comment by alangrafu** [comment]
The good part of deploying on a Raspberry Pi is that you self host everything, you own the whole stack.


I was able to make it work locally on my RPi4, but because yarn sucks, in many cases there is a timeout when fetching the packages. I can't create a PR, but the Dockerfile I used to build the image is the following


```
# Stage 1: Building the code
FROM node:16-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock ./

RUN ls -la && which yarn && pwd && yarn install --frozen-lockfile

COPY . .

# RUN npm --verbose install &&  npm run build &&  yarn build &&  yarn install --production --frozen-lockfile
RUN yarn build &&  yarn install --network-timeout=30000 --production --frozen-lockfile


# Stage 2: And then copy over node_modules, etc from that stage to the smaller base image
FROM node:16-alpine as production

WORKDIR /app

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

CMD ["node_modules/.bin/next", "start"]
```


Also, you may want to run an arm-friendly docker image. I found [this one](https://github.com/dimianstudio/minio-arm) that works.


@QingWei-Li I'm not a docker expert by any means, but it would be great if you could add this information in the documentation please? Thank you!

**Comment by alangrafu** [comment]
This may also close #84 BTW.

**Comment by aleJohnny** [comment]
Sorry for take to long to give a proper follow-up, I forgot about this issue.
So, I was using Raspbian when I opened this issue, which is 32-bit. In the end, I just switched to Ubuntu Server for RPi, it's 64-bit, and worked like a charm.

Thanks!
