### ISSUE TITLE
Git as backend?

### ISSUE THREAD

**Issue by alangrafu** [QingWei-Li/notea#93]
How easy/hard would be to support git as a backend? I envision two cases:

- automatic commit after the user hasn’t pressed a key for X seconds
- Explicit commit done by the user to save a version of the document as a commit.

Thoughts @QingWei-Li ?

**Comment by QingWei-Li** [comment]
At the beginning, I abstracted the storage provider base class. https://github.com/QingWei-Li/notea/blob/main/libs/server/store/providers/base.ts 

I am not sure if it will be complicated to implement these with Git, because I am based on the structure designed by s3. If you are interested, you can try it.
